### ISSUE TITLE
Error on Blender 2.92 Archlinux

### ISSUE THREAD

**Issue by Sinasta** [rpopovici/power-nodes#1]
Getting an error while activation on Linux (Arch). Could you please explain how to install the dependencies manually? i tried installing numba throught pip but still the same error. Thank you very much

Traceback (most recent call last):
  File "/home/sinasta/.config/blender/2.92/scripts/addons/power-nodes-main/powernodes/bool/csg/numba/__init__.py", line 3, in <module>
    import numba
ModuleNotFoundError: No module named 'numba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/blender/2.92/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/sinasta/.config/blender/2.92/scripts/addons/power-nodes-main/__init__.py", line 18, in <module>
    auto_load.init()
  File "/home/sinasta/.config/blender/2.92/scripts/addons/power-nodes-main/auto_load.py", line 23, in init
    modules = get_all_submodules(Path(__file__).parent)
  File "/home/sinasta/.config/blender/2.92/scripts/addons/power-nodes-main/auto_load.py", line 51, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
  File "/home/sinasta/.config/blender/2.92/scripts/addons/power-nodes-main/auto_load.py", line 55, in iter_submodules
    yield importlib.import_module("." + name, package_name)
  File "/usr/share/blender/2.92/python/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/sinasta/.config/blender/2.92/scripts/addons/power-nodes-main/powernodes/attribute_node.py", line 9, in <module>
    from . ops import *
  File "/home/sinasta/.config/blender/2.92/scripts/addons/power-nodes-main/powernodes/ops.py", line 20, in <module>
    from . bool.csg.numba.core import bool_csg_mesh
  File "/home/sinasta/.config/blender/2.92/scripts/addons/power-nodes-main/powernodes/bool/csg/numba/__init__.py", line 10, in <module>
    subprocess.check_call([PYTHON_PATH, '-m', 'pip', 'install', '--no-cache-dir', '--pre', 'numba'])
  File "/usr/share/blender/2.92/python/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/share/blender/2.92/python/bin/python3.7m', '-m', 'pip', 'install', '--no-cache-dir', '--pre', 'numba']' returned non-zero exit status 1.

**Comment by rpopovici** [comment]
@Sinasta I tested power-nodes only on Windows. It should work on linux as well. I don't know how blender is installed on linux.. On windows python is bundled with blender. And if you want to manually install python packages, you have to go to the install folder and run `./python.exe -m pip install --upgrade --target ../lib/site-packages numba` from python bin folder.

**Comment by Sinasta** [comment]
Thank you! I now installed Numba. Now it gives me a different error:

Traceback (most recent call last):
  File "/home/sinasta/.config/blender/2.92/scripts/site_package/numba/core/typeconv/typeconv.py", line 4, in <module>
    from numba.core.typeconv import _typeconv
ImportError: cannot import name '_typeconv' from 'numba.core.typeconv' (/home/sinasta/.config/blender/2.92/scripts/site_package/numba/core/typeconv/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sinasta/.config/blender/2.92/scripts/addons/power-nodes-main/powernodes/bool/csg/numba/__init__.py", line 3, in <module>
    import numba
  File "/home/sinasta/.config/blender/2.92/scripts/site_package/numba/__init__.py", line 24, in <module>
    from numba.misc.special import (
  File "/home/sinasta/.config/blender/2.92/scripts/site_package/numba/misc/special.py", line 3, in <module>
    from numba.core.typing.typeof import typeof
  File "/home/sinasta/.config/blender/2.92/scripts/site_package/numba/core/typing/__init__.py", line 1, in <module>
    from .context import BaseContext, Context
  File "/home/sinasta/.config/blender/2.92/scripts/site_package/numba/core/typing/context.py", line 11, in <module>
    from numba.core.typeconv import Conversion, rules
  File "/home/sinasta/.config/blender/2.92/scripts/site_package/numba/core/typeconv/rules.py", line 2, in <module>
    from .typeconv import TypeManager, TypeCastingRules
  File "/home/sinasta/.config/blender/2.92/scripts/site_package/numba/core/typeconv/typeconv.py", line 17, in <module>
    raise ImportError(msg % (url, reportme, str(e), sys.executable))
ImportError: Numba could not be imported.
If you are seeing this message and are undertaking Numba development work, you may need to re-run:

python setup.py build_ext --inplace

(Also, please check the development set up guide https://numba.pydata.org/numba-doc/latest/developer/contributing.html.)

If you are not working on Numba development:

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

The original error was: 'cannot import name '_typeconv' from 'numba.core.typeconv' (/home/sinasta/.config/blender/2.92/scripts/site_package/numba/core/typeconv/__init__.py)'
--------------------------------------------------------------------------------
If possible please include the following in your error report:

sys.executable: /usr/share/blender/2.92/python/bin/python3.7m


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/blender/2.92/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/sinasta/.config/blender/2.92/scripts/addons/power-nodes-main/__init__.py", line 18, in <module>
    auto_load.init()
  File "/home/sinasta/.config/blender/2.92/scripts/addons/power-nodes-main/auto_load.py", line 23, in init
    modules = get_all_submodules(Path(__file__).parent)
  File "/home/sinasta/.config/blender/2.92/scripts/addons/power-nodes-main/auto_load.py", line 51, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
  File "/home/sinasta/.config/blender/2.92/scripts/addons/power-nodes-main/auto_load.py", line 55, in iter_submodules
    yield importlib.import_module("." + name, package_name)
  File "/usr/share/blender/2.92/python/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/sinasta/.config/blender/2.92/scripts/addons/power-nodes-main/powernodes/attribute_node.py", line 9, in <module>
    from . ops import *
  File "/home/sinasta/.config/blender/2.92/scripts/addons/power-nodes-main/powernodes/ops.py", line 20, in <module>
    from . bool.csg.numba.core import bool_csg_mesh
  File "/home/sinasta/.config/blender/2.92/scripts/addons/power-nodes-main/powernodes/bool/csg/numba/__init__.py", line 10, in <module>
    subprocess.check_call([PYTHON_PATH, '-m', 'pip', 'install', '--no-cache-dir', '--pre', 'numba'])
  File "/usr/share/blender/2.92/python/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/share/blender/2.92/python/bin/python3.7m', '-m', 'pip', 'install', '--no-cache-dir', '--pre', 'numba']' returned non-zero exit status 1.

**Comment by rpopovici** [comment]
@Sinasta what version of python do you have? Python 3.9 is not supported in numba 0.52. They intend to release an update until the end of the year.. https://aur.archlinux.org/packages/python-numba/

**Comment by Sinasta** [comment]
Ok thank you very much. i will wait for the release than
